# Generated by Django 4.1.5 on 2023-03-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_contact_comment_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
